name: Pylint

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install fastapi
        pip install uvicorn
        pip install SQLAlchemy
        pip install psycopg2-binary
        pip install passlib
        pip install python-jose
        pip install aioredis
        pip install redis
        pip install fastapi-pagination[sqlalchemy]
        pip install scalar-fastapi
        pip install pydantic
        pip install pydantic-settings
        pip install slowapi
        pip install bcrypt
        pip install python-multipart
        pip install alembic
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
